### ISSUE TITLE
공지 이벤트 관리 이슈

### ISSUE THREAD

**Issue by bjh3311** [md2eoseo/se12-back#11]
1-25 : 등록된 공지/이벤트 선택 후 수정가능한 방법이 존재해야 함

- 공지/이벤트 관리화면에서 수정을 누르면 이미지를 변경 할 수 있는 버튼이 따로 없습니다.그래서 이미 등록된 공지/이벤트 이미지를 변경하지 못합니다.
- 상품 이미지를 수정할 수 있도록 이미지 업로드 기능을 수정 화면에 추가시켜야 할 것 같습니다.

**Comment by md2eoseo** [comment]
공지/이벤트 이미지를 수정할 수 있도록 양식에 이미지 수정 칸을 추가했습니다.
