### ISSUE TITLE
상품 관리 이슈

### ISSUE THREAD

**Issue by bjh3311** [md2eoseo/se12-back#12]
1-29 : 수정을 선택하면 상품 정보를 수정할 수 있어야 함
- 이미 등록된 상품을 수정 버튼을 누르면 이미지를 변경 할 수 있는 버튼이 따로 없습니다. 그래서 이미 등록된 상품은 이미지를 변경하지 못합니다.
- 상품 이미지를 수정할 수 있도록 이미지 업로드 기능을 수정 화면에 추가시켜야 할 것 같습니다.

1-34 : 상품명, 가격에 제약조건이 있으면 이를 검사하고 경고 표시
- 상품명의 제약조건을 알 수 없습니다.
- 또한 가격의 경우 0원 이하의 가격은 입력할 수 없지만 100억 이상의 값은 입력이 되고, 큰 값의 가격을 가진 상품을 등록할 시 에러화면으로 넘어갑니다(첨부화면 처럼 에러가 뜬다)
![1-34 가격 큰값넣었을시 오류](https://user-images.githubusercontent.com/76583684/120156234-c090d980-c22c-11eb-9b39-c4004b8dd5fa.JPG)
- 판매 가격 조건의 max 값도 설정하여 그 값 이상으로 입력할 수 없도록 제약을 걸어줘야 할 것 같습니다.

2-38 :상품 등록시 이미지를 여러 개 등록할 수 있어야 함
- 상품을 등록할 때 이미지를 계속 추가 할 수 있을거라 예상했지만 1개까지만 등록 되고 더 추가하려고 하면 이전에 등록된 이미지가 삭제가 됩니다.
- 이미지를 추가했을 때 기존에 등록했던 이미지가 남아있을 수 있도록 기능을 추가해야 할 것 같습니다.

**Comment by md2eoseo** [comment]
상품 등록할 때 이미지를 여러 개 등록할 수 있었지만 수정할 수는 없어서 이미지를 수정할 수 있도록 양식에 이미지 수정 칸을 추가했습니다.

**Comment by ufshg** [comment]
상품 가격의 제약조건을 0 ~ 2147483647 로 수정했습니다.

**Comment by md2eoseo** [comment]
제약조건은 GraphQL에서 사용할 수 있는 int 최대값과 0으로 설정했습니다.
